image: golang:latest

workflow:
  rules:
    - when: always

stages:
- security
- test
- build

format:
  stage: test
  script:
  - cd src
  - go mod tidy
  - go fmt ./...
  - go vet ./...
  - go test ./...

compile:
  stage: build
  script:
  - cd src
  - mkdir -p mybinaries
  - go mod tidy
  - go build -o mybinaries ./...

sast:
  stage: security
include:
- template: Security/SAST.gitlab-ci.yml