package injector

import "moncaveau/database"

var (
	regions = []database.WineRegion{
		// Regions

		{Name: "Auvergne-Rhône-Alpes", Country: "France"},
		{Name: "Hauts-de-France", Country: "France"},
		{Name: "Provence-Alpes-Côte d'Azur", Country: "France"},
		{Name: "Grand Est", Country: "France"},
		{Name: "Occitanie", Country: "France"},
		{Name: "Normandie", Country: "France"},
		{Name: "Nouvelle-Aquitaine", Country: "France"},
		{Name: "Centre-Val de Loire", Country: "France"},
		{Name: "Bourgogne-Franche-Comté", Country: "France"},
		{Name: "Bretagne", Country: "France"},
		{Name: "Corse", Country: "France"},
		{Name: "Pays de la Loire", Country: "France"},
		{Name: "Île-de-France", Country: "France"},
		{Name: "Guadeloupe", Country: "France"},
		{Name: "Martinique", Country: "France"},
		{Name: "Guyane", Country: "France"},
		{Name: "La Réunion", Country: "France"},
		{Name: "Mayotte", Country: "France"},

		// Departments

		{Name: "Ain", Country: "France"},
		{Name: "Aisne", Country: "France"},
		{Name: "Allier", Country: "France"},
		{Name: "Alpes-de-Haute-Provence", Country: "France"},
		{Name: "Hautes-Alpes", Country: "France"},
		{Name: "Alpes-Maritimes", Country: "France"},
		{Name: "Ardèche", Country: "France"},
		{Name: "Ardennes", Country: "France"},
		{Name: "Ariège", Country: "France"},
		{Name: "Aube", Country: "France"},
		{Name: "Aude", Country: "France"},
		{Name: "Aveyron", Country: "France"},
		{Name: "Bouches-du-Rhône", Country: "France"},
		{Name: "Calvados", Country: "France"},
		{Name: "Cantal", Country: "France"},
		{Name: "Charente", Country: "France"},
		{Name: "Charente-Maritime", Country: "France"},
		{Name: "Cher", Country: "France"},
		{Name: "Corrèze", Country: "France"},
		{Name: "Côte-d'Or", Country: "France"},
		{Name: "Côtes-d'Armor", Country: "France"},
		{Name: "Creuse", Country: "France"},
		{Name: "Dordogne", Country: "France"},
		{Name: "Doubs", Country: "France"},
		{Name: "Drôme", Country: "France"},
		{Name: "Eure", Country: "France"},
		{Name: "Eure-et-Loir", Country: "France"},
		{Name: "Finistère", Country: "France"},
		{Name: "Corse-du-Sud", Country: "France"},
		{Name: "Haute-Corse", Country: "France"},
		{Name: "Gard", Country: "France"},
		{Name: "Haute-Garonne", Country: "France"},
		{Name: "Gers", Country: "France"},
		{Name: "Gironde", Country: "France"},
		{Name: "Hérault", Country: "France"},
		{Name: "Ille-et-Vilaine", Country: "France"},
		{Name: "Indre", Country: "France"},
		{Name: "Indre-et-Loire", Country: "France"},
		{Name: "Isère", Country: "France"},
		{Name: "Jura", Country: "France"},
		{Name: "Landes", Country: "France"},
		{Name: "Loir-et-Cher", Country: "France"},
		{Name: "Loire", Country: "France"},
		{Name: "Haute-Loire", Country: "France"},
		{Name: "Loire-Atlantique", Country: "France"},
		{Name: "Loiret", Country: "France"},
		{Name: "Lot", Country: "France"},
		{Name: "Lot-et-Garonne", Country: "France"},
		{Name: "Lozère", Country: "France"},
		{Name: "Maine-et-Loire", Country: "France"},
		{Name: "Manche", Country: "France"},
		{Name: "Marne", Country: "France"},
		{Name: "Haute-Marne", Country: "France"},
		{Name: "Mayenne", Country: "France"},
		{Name: "Meurthe-et-Moselle", Country: "France"},
		{Name: "Meuse", Country: "France"},
		{Name: "Morbihan", Country: "France"},
		{Name: "Moselle", Country: "France"},
		{Name: "Nièvre", Country: "France"},
		{Name: "Nord", Country: "France"},
		{Name: "Oise", Country: "France"},
		{Name: "Orne", Country: "France"},
		{Name: "Pas-de-Calais", Country: "France"},
		{Name: "Puy-de-Dôme", Country: "France"},
		{Name: "Pyrénées-Atlantiques", Country: "France"},
		{Name: "Hautes-Pyrénées", Country: "France"},
		{Name: "Pyrénées-Orientales", Country: "France"},
		{Name: "Bas-Rhin", Country: "France"},
		{Name: "Haut-Rhin", Country: "France"},
		{Name: "Rhône", Country: "France"},
		{Name: "Haute-Saône", Country: "France"},
		{Name: "Saône-et-Loire", Country: "France"},
		{Name: "Sarthe", Country: "France"},
		{Name: "Savoie", Country: "France"},
		{Name: "Haute-Savoie", Country: "France"},
		{Name: "Paris", Country: "France"},
		{Name: "Seine-Maritime", Country: "France"},
		{Name: "Seine-et-Marne", Country: "France"},
		{Name: "Yvelines", Country: "France"},
		{Name: "Deux-Sèvres", Country: "France"},
		{Name: "Somme", Country: "France"},
		{Name: "Tarn", Country: "France"},
		{Name: "Tarn-et-Garonne", Country: "France"},
		{Name: "Var", Country: "France"},
		{Name: "Vaucluse", Country: "France"},
		{Name: "Vendée", Country: "France"},
		{Name: "Vienne", Country: "France"},
		{Name: "Haute-Vienne", Country: "France"},
		{Name: "Vosges", Country: "France"},
		{Name: "Yonne", Country: "France"},
		{Name: "Territoire de Belfort", Country: "France"},
		{Name: "Essonne", Country: "France"},
		{Name: "Hauts-de-Seine", Country: "France"},
		{Name: "Seine-Saint-Denis", Country: "France"},
		{Name: "Val-de-Marne", Country: "France"},
		{Name: "Val-d'Oise", Country: "France"},
	}

	types = []database.WineType{
		{Name: "Rouge"},
		{Name: "Blanc"},
		{Name: "Rosé"},
		{Name: "Champagne"},
		{Name: "Crémant"},
	}

	bottleSizes = []database.WineBottleSize{
		{Size: 375, Name: "Demi-bouteille"},
		{Size: 750, Name: "Bouteille"},
		{Size: 1500, Name: "Magnum"},
		{Size: 3000, Name: "Jéroboam"},
		{Size: 4500, Name: "Réhoboam"},
		{Size: 6000, Name: "Mathusalem)"},
		{Size: 9000, Name: "Salmanazar"},
		{Size: 12000, Name: "Balthazar)"},
		{Size: 15000, Name: "Nabuchodonosor"},
		{Size: 18000, Name: "Melchior"},
	}
)
