name: Go CI/CD

on: ["push", "pull_request"]

jobs:
  format:
    name: Format & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0

      - name: Run go fmt, go vet, and go test
        run: |
          cd src
          go mod tidy
          go fmt ./...
          go vet ./...
          go test ./...

  compile:
    name: Compile Go Build
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0

      - name: Build application
        run: |
          cd src
          mkdir -p mybinaries
          go mod tidy
          echo "Regular Build - Building without versioning"
          go build -o mybinaries ./...
